# Generated by Django 5.0.1 on 2024-02-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_addtailors_assigned_works_addtailors_completed_works_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bill_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
