# Generated by Django 5.0.1 on 2024-02-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_customer_bill_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='addtailors',
            managers=[
            ],
        ),
    ]
